name: Main

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Show files in CWD
        run: ls
        
      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          command: install
          #github_oauth: ${{ secret.GITHUB_OAUTH }}
    
      - name: Install PrestaShop / php-dev-tools
        run: |
          composer require --dev prestashop/php-dev-tools
          
      - name: Apply Coding Standards
        run: php vendor/bin/php-cs-fixer fix 8/pitchprint
      
      - name: Commit the version updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prestashop Php coding standard
          branch: master
      # - name: Just checking
      #   run: echo 
      # - name: Checkout
      # - name: Create asset
      #   run: cd .. && zip testBump.zip testBump/* -r && cd testBump/
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body_path: "CHANGELOG.txt"
      #     name: "Print.App - PrestaShop 1.7.x - ${{ github.ref_name }}"
      #     files: "../testBump.zip"